apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy91c2Vycw== # base64 encoded
  jwt-secret: c3VwZXJzZWNyZXRrZXk= # base64 encoded
