apiVersion: v1
kind: Secret
metadata:
    name: basic-auth-secret
    namespace: default
type: Opaque
data:
    users: YWRtaW46JGFwcjEkazFaekFnWG0kREZTLzJ3Ukt2UEhXTGJHT1ZCMHhnMQ== # admin/admin in htpasswd format, base64 encoded
