# infrastructure/kubernetes/user-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-service
spec:
    selector:
        matchLabels:
            app: user-service
    template:
        metadata:
            labels:
                app: user-service
        spec:
            containers:
                - name: user-service
                  image: user-service:1.0.3
                  ports:
                      - containerPort: 3000
                  env:
                      - name: MONGODB_URI
                        value: "mongodb://mongodb:27017/users"
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "250m"
                      limits:
                          memory: "256Mi"
                          cpu: "500m"
